services:
  monit:
    image: extrafein/monit
    build:
      context: https://github.com/extrafein/monit.git
      args:
        # you can find supported/prepared architektures on the monit homepage
        # https://mmonit.com/monit/
        # see pre compiled binaries
        architecture: linux-x64
    restart: always
